crop_info = {
    "rice": {
        "temperature": "20°C - 35°C",
        "ph": "5.5 - 7.0",
        "rainfall": "100 - 200 cm",
        "tips": "Rice needs plenty of water and warm climate.",
        "harvest_time": "3 - 6 months",
    },
    "wheat": {
        "temperature": "12°C - 25°C",
        "ph": "6.0 - 7.0",
        "rainfall": "30 - 90 cm",
        "tips": "Requires cool weather during growth and dry weather for harvest.",
        "harvest_time": "4 - 6 months",
    },
    "ground nuts": {
        "temperature": "20°C - 30°C",
        "ph": "6.0 - 7.0",
        "rainfall": "50 - 100 cm",
        "tips": "Require sandy loam soil and good drainage.",
        "harvest_time": "4 - 5 months",
    },
    "orange": {
        "temperature": "15°C - 30°C",
        "ph": "5.5 - 6.5",
        "rainfall": "75 - 125 cm",
        "tips": "Needs well-drained soil and regular watering.",
        "harvest_time": "6 - 12 months",
    },
    "maize": {
        "temperature": "18°C - 27°C",
        "ph": "5.8 - 7.0",
        "rainfall": "50 - 100 cm",
        "tips": "Requires well-drained fertile soil and moderate rainfall.",
        "harvest_time": "3 - 4 months",
    },
    "cotton": {
        "temperature": "21°C - 30°C",
        "ph": "5.5 - 7.5",
        "rainfall": "50 - 100 cm",
        "tips": "Needs black soil rich in lime and moisture.",
        "harvest_time": "6 - 7 months",
    },
    "sugarcane": {
        "temperature": "20°C - 32°C",
        "ph": "6.0 - 7.5",
        "rainfall": "75 - 150 cm",
        "tips": "Requires plenty of sunshine and water.",
        "harvest_time": "10 - 18 months",
    },
    "pulses": {
        "temperature": "20°C - 30°C",
        "ph": "6.0 - 7.5",
        "rainfall": "30 - 60 cm",
        "tips": "Pulses grow well in well-drained loamy soil.",
        "harvest_time": "3 - 4 months",
    },
    "millets": {
        "temperature": "25°C - 30°C",
        "ph": "5.5 - 7.0",
        "rainfall": "40 - 70 cm",
        "tips": "Require less water and grow well in poor soil.",
        "harvest_time": "3 - 4 months",
    },
    "potato": {
        "temperature": "15°C - 20°C",
        "ph": "5.0 - 6.0",
        "rainfall": "50 - 75 cm",
        "tips": "Prefers well-drained sandy loam soil.",
        "harvest_time": "3 - 4 months",
    },
    "tomato": {
        "temperature": "20°C - 25°C",
        "ph": "6.0 - 7.0",
        "rainfall": "60 - 100 cm",
        "tips": "Requires warm, frost-free climate and well-drained soil.",
        "harvest_time": "2 - 3 months",
    },
    "banana": {
        "temperature": "26°C - 30°C",
        "ph": "5.5 - 7.0",
        "rainfall": "100 - 200 cm",
        "tips": "Needs rich, well-drained soil and frequent watering.",
        "harvest_time": "9 - 12 months",
    },
    "coconut": {
        "temperature": "27°C - 32°C",
        "ph": "5.0 - 8.0",
        "rainfall": "100 - 200 cm",
        "tips": "Grows well in sandy, well-drained soils with high humidity.",
        "harvest_time": "5 - 7 years",
    },
    "soybean": {
        "temperature": "20°C - 30°C",
        "ph": "6.0 - 7.5",
        "rainfall": "50 - 70 cm",
        "tips": "Needs well-drained fertile soil and moderate rainfall.",
        "harvest_time": "3 - 4 months",
    },
    # Add more as needed
}
